version: "3.3"

services: 
  web:
    image: nginx:latest
    ports:
      - "9100:9100"
    volumes:
      - ./:/CTM_UI
      - ./ctm-ui.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    image: php:fpm
    volumes:
        - ./:/CTM_UI
    networks:
        - code-network

networks:
    code-network:
        driver: bridge
