version: "3.3"

services: 
  web:
    image: nginx:latest
    ports:
      - "9100:80"
    volumes:
      - ./:/code
      - ./ctm-ui.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    image: php:fpm
    volumes:
        - ./:/code
    networks:
        - code-network

networks:
    code-network:
        driver: bridge
