version: "3.3"

services: 
  web:
    container_name: autoseq-launcher-ui
    image: nginx:latest
    ports:
      - "9100:9100"
    volumes:
      - ./:/autoseq-launcher-ui
      - ./autoseq_launcher_ui.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    container_name: autoseq-launcher-ui-php
    image: php:fpm
    volumes:
        - ./:/autoseq-launcher-ui
    networks:
        - code-network

networks:
    code-network:
        driver: bridge
